using System.Text;
using SchemaScope.Core.Model;

namespace SchemaScope.Core.Normalization;

/// <summary>
/// Renders structural objects (tables, table types, sequences, synonyms...) as a
/// deterministic T-SQL script.
///
/// This is the trick that makes structural compares formatting proof: both sides
/// are generated by the same code from catalog metadata, so any text difference
/// is a real difference. It doubles as the readable script shown in the diff view.
///
/// Deliberately no column alignment padding - padding makes one renamed column
/// light up every line in the diff.
/// </summary>
public static class CanonicalScriptWriter
{
    public static string Write(DbObject o, CompareOptions opt) => o.Type switch
    {
        DbObjectType.Table => WriteTable(o, opt, asTableType: false),
        DbObjectType.TableType => WriteTable(o, opt, asTableType: true),
        DbObjectType.UserDefinedType => WriteUserType(o),
        DbObjectType.Sequence => WriteSequence(o),
        DbObjectType.Synonym => WriteSynonym(o),
        DbObjectType.Schema => WriteSchema(o),
        _ => o.Definition ?? ""
    };

    private static string Q(string name) => $"[{name.Replace("]", "]]")}]";

    private static string WriteSchema(DbObject o)
    {
        var owner = o.Properties.GetValueOrDefault("owner");
        return string.IsNullOrEmpty(owner)
            ? $"CREATE SCHEMA {Q(o.Name)};"
            : $"CREATE SCHEMA {Q(o.Name)} AUTHORIZATION {Q(owner)};";
    }

    private static string WriteSynonym(DbObject o) =>
        $"CREATE SYNONYM {Q(o.Schema)}.{Q(o.Name)} FOR {o.Properties.GetValueOrDefault("baseObject")};";

    private static string WriteUserType(DbObject o)
    {
        var baseType = o.Properties.GetValueOrDefault("baseType") ?? "";
        var nullable = o.Properties.GetValueOrDefault("isNullable") == "1" ? "NULL" : "NOT NULL";
        return $"CREATE TYPE {Q(o.Schema)}.{Q(o.Name)} FROM {baseType} {nullable};";
    }

    private static string WriteSequence(DbObject o)
    {
        var sb = new StringBuilder();
        sb.Append($"CREATE SEQUENCE {Q(o.Schema)}.{Q(o.Name)}");
        sb.Append($" AS {o.Properties.GetValueOrDefault("type")}");
        sb.Append($" START WITH {o.Properties.GetValueOrDefault("startValue")}");
        sb.Append($" INCREMENT BY {o.Properties.GetValueOrDefault("increment")}");

        var min = o.Properties.GetValueOrDefault("minValue");
        var max = o.Properties.GetValueOrDefault("maxValue");
        sb.Append(string.IsNullOrEmpty(min) ? " NO MINVALUE" : $" MINVALUE {min}");
        sb.Append(string.IsNullOrEmpty(max) ? " NO MAXVALUE" : $" MAXVALUE {max}");
        sb.Append(o.Properties.GetValueOrDefault("isCycling") == "1" ? " CYCLE" : " NO CYCLE");

        var cache = o.Properties.GetValueOrDefault("cacheSize");
        sb.Append(o.Properties.GetValueOrDefault("isCached") == "1"
            ? string.IsNullOrEmpty(cache) ? " CACHE" : $" CACHE {cache}"
            : " NO CACHE");

        sb.Append(';');
        return sb.ToString();
    }

    private static string WriteTable(DbObject o, CompareOptions opt, bool asTableType)
    {
        var sb = new StringBuilder(512);
        var header = asTableType
            ? $"CREATE TYPE {Q(o.Schema)}.{Q(o.Name)} AS TABLE ("
            : $"CREATE TABLE {Q(o.Schema)}.{Q(o.Name)} (";
        sb.Append(header).Append('\n');

        var columns = opt.IgnoreColumnOrder
            ? o.Columns.OrderBy(c => c.Name, StringComparer.OrdinalIgnoreCase).ToList()
            : o.Columns.OrderBy(c => c.Ordinal).ToList();

        var lines = new List<string>(columns.Count + 8);
        foreach (var c in columns)
            lines.Add("    " + ColumnLine(c, o, opt));

        // PRIMARY KEY and UNIQUE live inside the CREATE TABLE body
        foreach (var ix in o.Indexes
                     .Where(i => i.IsPrimaryKey || i.IsUniqueConstraint)
                     .OrderBy(i => i.IsPrimaryKey ? 0 : 1)
                     .ThenBy(i => i.Name, StringComparer.OrdinalIgnoreCase))
            lines.Add("    " + KeyConstraintLine(ix, opt));

        foreach (var ck in o.Constraints
                     .Where(x => x.Kind == ConstraintKind.Check)
                     .OrderBy(x => SortKeyFor(x, opt), StringComparer.OrdinalIgnoreCase))
            lines.Add("    " + CheckConstraintLine(ck, opt));

        sb.Append(string.Join(",\n", lines)).Append("\n);\n");

        // standalone indexes
        foreach (var ix in o.Indexes
                     .Where(i => !i.IsPrimaryKey && !i.IsUniqueConstraint)
                     .OrderBy(i => i.Name, StringComparer.OrdinalIgnoreCase))
            sb.Append(IndexStatement(ix, o, opt)).Append('\n');

        // foreign keys
        foreach (var fk in o.ForeignKeys.OrderBy(f => f.Name, StringComparer.OrdinalIgnoreCase))
            sb.Append(ForeignKeyStatement(fk, o, opt)).Append('\n');

        return sb.ToString().TrimEnd('\n');
    }

    private static string SortKeyFor(ConstraintInfo c, CompareOptions opt) =>
        opt.IgnoreSystemNamedConstraints && c.IsSystemNamed ? c.Definition : c.Name;

    private static string ColumnLine(ColumnInfo c, DbObject o, CompareOptions opt)
    {
        var sb = new StringBuilder(96);
        sb.Append(Q(c.Name)).Append(' ');

        if (c.IsComputed)
        {
            sb.Append("AS ").Append(c.ComputedDefinition);
            if (c.IsPersisted)
            {
                sb.Append(" PERSISTED");
                if (!c.IsNullable) sb.Append(" NOT NULL");
            }
            return sb.ToString();
        }

        sb.Append(c.DataType);

        if (!opt.IgnoreCollation && !string.IsNullOrEmpty(c.Collation))
            sb.Append(" COLLATE ").Append(c.Collation);

        if (c.IsSparse) sb.Append(" SPARSE");

        if (c.IsIdentity)
            sb.Append(opt.IgnoreIdentitySeed
                ? " IDENTITY"
                : $" IDENTITY ({c.IdentitySeed}, {c.IdentityIncrement})");

        if (c.IsRowGuidCol) sb.Append(" ROWGUIDCOL");

        sb.Append(c.IsNullable ? " NULL" : " NOT NULL");

        // Inline the DEFAULT when its name is system generated and we are told to
        // ignore those - DF__Table__Col__1A2B3C differs on every server for no reason.
        var def = o.Constraints.FirstOrDefault(x =>
            x.Kind == ConstraintKind.Default &&
            string.Equals(x.ColumnName, c.Name, StringComparison.OrdinalIgnoreCase));

        if (def is not null)
        {
            sb.Append(opt.IgnoreSystemNamedConstraints && def.IsSystemNamed
                ? $" DEFAULT {def.Definition}"
                : $" CONSTRAINT {Q(def.Name)} DEFAULT {def.Definition}");
        }

        return sb.ToString();
    }

    private static string KeyConstraintLine(IndexInfo ix, CompareOptions opt)
    {
        var sb = new StringBuilder(96);
        sb.Append("CONSTRAINT ").Append(Q(ix.Name)).Append(' ');
        sb.Append(ix.IsPrimaryKey ? "PRIMARY KEY " : "UNIQUE ");
        sb.Append(ix.TypeDesc.Contains("CLUSTERED", StringComparison.OrdinalIgnoreCase)
            ? ix.TypeDesc.ToUpperInvariant()
            : "NONCLUSTERED");
        sb.Append(" (").Append(KeyColumnList(ix)).Append(')');
        sb.Append(IndexWithClause(ix, opt));
        return sb.ToString();
    }

    private static string CheckConstraintLine(ConstraintInfo c, CompareOptions opt)
    {
        var named = !(opt.IgnoreSystemNamedConstraints && c.IsSystemNamed);
        var sb = new StringBuilder(96);
        if (named) sb.Append("CONSTRAINT ").Append(Q(c.Name)).Append(' ');
        sb.Append("CHECK ").Append(c.Definition);
        if (c.IsDisabled) sb.Append(" /* disabled */");
        return sb.ToString();
    }

    private static string KeyColumnList(IndexInfo ix) =>
        string.Join(", ", ix.KeyColumns
            .OrderBy(k => k.Ordinal)
            .Select(k => $"{Q(k.Name)} {(k.Descending ? "DESC" : "ASC")}"));

    private static string IndexWithClause(IndexInfo ix, CompareOptions opt)
    {
        var parts = new List<string>();
        if (!opt.IgnoreIndexPadding && ix.IsPadded) parts.Add("PAD_INDEX = ON");
        if (!opt.IgnoreFillFactor && ix.FillFactor > 0) parts.Add($"FILLFACTOR = {ix.FillFactor}");
        if (ix.IgnoreDupKey) parts.Add("IGNORE_DUP_KEY = ON");
        return parts.Count == 0 ? "" : $" WITH ({string.Join(", ", parts)})";
    }

    private static string IndexStatement(IndexInfo ix, DbObject o, CompareOptions opt)
    {
        var sb = new StringBuilder(128);
        sb.Append("CREATE ");
        if (ix.IsUnique) sb.Append("UNIQUE ");
        sb.Append(ix.TypeDesc.ToUpperInvariant()).Append(" INDEX ");
        sb.Append(Q(ix.Name)).Append(" ON ").Append(Q(o.Schema)).Append('.').Append(Q(o.Name));
        sb.Append(" (").Append(KeyColumnList(ix)).Append(')');

        if (ix.IncludedColumns.Count > 0)
            sb.Append(" INCLUDE (")
              .Append(string.Join(", ", ix.IncludedColumns.OrderBy(c => c, StringComparer.OrdinalIgnoreCase).Select(Q)))
              .Append(')');

        if (!string.IsNullOrEmpty(ix.FilterDefinition))
            sb.Append(" WHERE ").Append(ix.FilterDefinition);

        sb.Append(IndexWithClause(ix, opt));

        if (!opt.IgnoreFileGroups && !string.IsNullOrEmpty(ix.DataSpace))
            sb.Append(" ON ").Append(Q(ix.DataSpace));

        if (ix.IsDisabled) sb.Append(" /* disabled */");

        sb.Append(';');
        return sb.ToString();
    }

    private static string ForeignKeyStatement(ForeignKeyInfo fk, DbObject o, CompareOptions opt)
    {
        var sb = new StringBuilder(160);
        sb.Append("ALTER TABLE ").Append(Q(o.Schema)).Append('.').Append(Q(o.Name));
        sb.Append(" ADD CONSTRAINT ").Append(Q(fk.Name)).Append(" FOREIGN KEY (");
        sb.Append(string.Join(", ", fk.Columns.Select(Q))).Append(')');
        sb.Append(" REFERENCES ").Append(Q(fk.ReferencedSchema)).Append('.').Append(Q(fk.ReferencedTable));
        sb.Append(" (").Append(string.Join(", ", fk.ReferencedColumns.Select(Q))).Append(')');

        if (fk.DeleteAction != "NO_ACTION") sb.Append(" ON DELETE ").Append(fk.DeleteAction.Replace('_', ' '));
        if (fk.UpdateAction != "NO_ACTION") sb.Append(" ON UPDATE ").Append(fk.UpdateAction.Replace('_', ' '));
        if (fk.IsDisabled) sb.Append(" /* disabled */");
        if (fk.IsNotTrusted) sb.Append(" /* not trusted */");

        sb.Append(';');
        return sb.ToString();
    }
}
